### ISSUE TITLE
A fatal error：ModuleNotFoundError: No module named 'psutil'

### ISSUE THREAD

**Issue by MBRjun** [bmyjacks/Multic-Toolbox#1]
# A FATAL ERROR
## BUG ID = 1
在版本0.0.4的Multic-Toolbox中，由于库缺失，在`import psutil`报错`ModuleNotFoundError: No module named 'psutil'`

**Comment by bmyjacks** [comment]
You can try `$ pip3 install psutil`

**Comment by Konjac0629** [comment]
您好，
感谢您选择HOStudio。
您所描述的问题通常是因为没有安装psutil这个Python库，
如果您有安装python包管理工具pip，您可以使用`pip3 install psutil`命令来安装这个Python库，
如果您没有安装python包管理工具pip，您可以手动安装psutil库以解决此问题。

          此致
HOStudio中文支持
