### ISSUE TITLE
A Fatal error:No such file or directory

### ISSUE THREAD

**Issue by MBRjun** [bmyjacks/Multic-Toolbox#2]
#A fatal ERROR
## BUGID = 2
问题较为复杂，是在强制修复bug #1的另一个错误
Tool's version: V0.0.2

##########System info##########
Traceback (most recent call last):
  File "C:\Users\zyn19\OneDrive\桌面\HH.py", line 39, in <module>
    load_list = get_load()[0:3]
  File "C:\Users\zyn19\OneDrive\桌面\HH.py", line 36, in get_load
    f = open("/proc/loadavg")
FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadavg'

**Comment by bmyjacks** [comment]
You should run it on Linux(such as Ububtu, Debian, CentOS, etc.)

**Comment by Konjac0629** [comment]
您好，
感谢您选择HOStudio。
您所描述的问题通常是因为在非Linux系统运行本程序而导致的，
您需要使用Linux系统（如Ubuntu，Debian，CentOS）来运行本程序。
          此致
HOStudio中文支持
